name: "Stream to hae.sh"
description: Send data to a hae.sh stream
author: "hae.sh GmbH"
inputs:
  haesh_stream_id:
    description: The header value, i.e. the secret API key itself
    required: true
  haesh_stream_header_name:
    description: The stream ID
    required: true
  haesh_stream_header_value:
    description: The header name of the API key
    required: true
runs:
  using: "node16"
  main: "dist/main.js"
