description: Send data to a hae.sh stream
inputs:
  haesh_stream_id:
    description: The header value, i.e. the secret API key itself
    required: true
  haesh_stream_header_name:
    description: The stream ID
    required: true
  haesh_stream_header_value:
    description: The header name of the API key
    required: true
name: 'Stream to hae.sh'
runs:
  steps:
    - name: Cancel previous runs
      uses: styfle/cancel-workflow-action@0.11.0
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Install node 18
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Install dependencies
      uses: borales/actions-yarn@v4
      with:
        cmd: install
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: Send data to hae.sh
      env:
        HAESH_STREAM_ID: ${{ inputs.haesh_stream_id }}
        HAESH_STREAM_HEADER_NAME: ${{ inputs.haesh_stream_header_name }}
        HAESH_STREAM_HEADER_VALUE: ${{ inputs.haesh_stream_header_value }}
      run: commit.sh
      shell: bash
  using: 'composite'
